# Generated by Django 4.2.8 on 2024-01-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0010_alter_academicemployeecategory_employee_category_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('salary', models.PositiveIntegerField()),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')])),
                ('status', models.BooleanField(default=True)),
                ('desigid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicdesignation')),
                ('dptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicdepartment')),
                ('empcatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicemployeecategory')),
                ('qualifid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicqualification')),
            ],
        ),
        migrations.CreateModel(
            name='scd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicclass')),
                ('divid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicdivision')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
                ('subid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicsubject')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='empdpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('dptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicdepartment')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='empdesig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('desigid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.academicdesignation')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
    ]
