# Generated by Django 4.2.8 on 2023-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0005_academicdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
