# Generated by Django 4.2.8 on 2023-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0006_academicemployeecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicemployeecategory',
            old_name='area',
            new_name='employee_category_name',
        ),
        migrations.RemoveField(
            model_name='academicemployeecategory',
            name='name',
        ),
        migrations.AddField(
            model_name='academicemployeecategory',
            name='employee_category_area',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='academicemployeecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
