# Generated by Django 4.2.8 on 2023-12-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0007_rename_area_academicemployeecategory_employee_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicemployeecategory',
            name='employee_category_area',
            field=models.IntegerField(),
        ),
    ]
