# Generated by Django 4.2.8 on 2023-12-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0008_alter_academicemployeecategory_employee_category_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicemployeecategory',
            name='employee_category_area',
            field=models.IntegerField(choices=[(1, 'Accountant'), (2, 'Cafeteria'), (3, 'Teacher'), (4, 'Library'), (5, 'Other')]),
        ),
    ]
