# Generated by Django 4.2.8 on 2024-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0009_alter_academicemployeecategory_employee_category_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicemployeecategory',
            name='employee_category_area',
            field=models.IntegerField(choices=[(1, 'Accountant'), (4, 'Cafeteria'), (2, 'Teacher'), (3, 'Library'), (5, 'Other')]),
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(to='admin_master.academicclass')),
            ],
        ),
    ]
